server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: '0817'
  session:
    store-type: none
mybatis:
  type-aliases-package: com.ttyc.security.demo.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
i-security:
  browser:
    login-type: JSON
    login-page: /demo-login.html
    signup-page: /demo-signup.html
    remeberme-time: 60
  social:
    qq:
      appId: 101514119
      appKey: f8f2ae2996d89a153c5a129fef1cfd02