server:
  port: 8088
spring:
  session:
    store-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
i-security:
  browser:
    login-type: JSON
    login-page: demo-login.html
    remeberme-time: 60
