server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: '0817'
  session:
    store-type: none
i-security:
  browser:
    login-type: JSON
    login-page: demo-login.html
    remeberme-time: 60
